config/routes.rb
Rails.application.routes.draw do
  resources :emergencia
  root 'emergencia#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emergencium.rb
class Emergencium < ApplicationRecord
    geocoded_by :address
    after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/emergencia_controller.rb
class EmergenciaController < ApplicationController
  before_action :set_emergencium, only: [:show, :edit, :update, :destroy]

  # GET /emergencia
  # GET /emergencia.json
  def index
    @emergencia = Emergencium.all
    @hash = Gmaps4rails.build_markers(@emergencia) do |emergencia, marker|
  marker.lat emergencia.latitude
  marker.lng emergencia.longitude
  marker.infowindow emergencia.descrption
  marker.picture({
    "url" => 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png',
    "height" => 32,
    "width" => 32
  })
  marker.json({title: emergencia.title})
end

  end

  # GET /emergencia/1
  # GET /emergencia/1.json
  def show
  end

  # GET /emergencia/new
  def new
    @emergencium = Emergencium.new
  end

  # GET /emergencia/1/edit
  def edit
  end

  # POST /emergencia
  # POST /emergencia.json
  def create
    @emergencium = Emergencium.new(emergencium_params)

    respond_to do |format|
      if @emergencium.save
        format.html { redirect_to @emergencium, notice: 'Emergencium was successfully created.' }
        format.json { render :show, status: :created, location: @emergencium }
      else
        format.html { render :new }
        format.json { render json: @emergencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emergencia/1
  # PATCH/PUT /emergencia/1.json
  def update
    respond_to do |format|
      if @emergencium.update(emergencium_params)
        format.html { redirect_to @emergencium, notice: 'Emergencium was successfully updated.' }
        format.json { render :show, status: :ok, location: @emergencium }
      else
        format.html { render :edit }
        format.json { render json: @emergencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emergencia/1
  # DELETE /emergencia/1.json
  def destroy
    @emergencium.destroy
    respond_to do |format|
      format.html { redirect_to emergencia_url, notice: 'Emergencium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emergencium
      @emergencium = Emergencium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emergencium_params
      params.require(:emergencium).permit(:latitude, :longitude, :address, :descrption, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emergencia_helper.rb
module EmergenciaHelper
end

app/views/emergencia/_form.html.erb
<%= form_with(model: emergencium, local: true) do |form| %>
  <% if emergencium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(emergencium.errors.count, "error") %> prohibited this emergencium from being saved:</h2>

      <ul>
      <% emergencium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :emergencium_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :emergencium_longitude %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :emergencium_address %>
  </div>

  <div class="field">
    <%= form.label :descrption %>
    <%= form.text_area :descrption, id: :emergencium_descrption %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :emergencium_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/emergencia/edit.html.erb
<h1>Editing Emergencium</h1>

<%= render 'form', emergencium: @emergencium %>

<%= link_to 'Show', @emergencium %> |
<%= link_to 'Back', emergencia_path %>

app/views/emergencia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Emergencia</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th>Descrption</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emergencia.each do |emergencium| %>
      <tr>
        <td><%= emergencium.latitude %></td>
        <td><%= emergencium.longitude %></td>
        <td><%= emergencium.address %></td>
        <td><%= emergencium.descrption %></td>
        <td><%= emergencium.title %></td>
        <td><%= link_to 'Show', emergencium %></td>
        <td><%= link_to 'Edit', edit_emergencium_path(emergencium) %></td>
        <td><%= link_to 'Destroy', emergencium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <div style='width: 800px;'>
      <div id="map" style='width: 800px; height: 400px;'></div>
    </div>
  </tbody>
</table>

<br>

<%= link_to 'New Emergencium', new_emergencium_path %>
<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/emergencia/new.html.erb
<h1>New Emergencium</h1>

<%= render 'form', emergencium: @emergencium %>

<%= link_to 'Back', emergencia_path %>

app/views/emergencia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @emergencium.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @emergencium.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @emergencium.address %>
</p>

<p>
  <strong>Descrption:</strong>
  <%= @emergencium.descrption %>
</p>

<p>
  <strong>Title:</strong>
  <%= @emergencium.title %>
</p>

<%= link_to 'Edit', edit_emergencium_path(@emergencium) %> |
<%= link_to 'Back', emergencia_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>COED</title>
    <%= csrf_meta_tags %>
    <script src="//maps.google.com/maps/api/js?key=AIzaSyCTH5GYI0cSg3iT74UQwQQGSOdXKchdLS4"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>